
"ff auto adding comments on next line
" so you can cut and paste reliably
" http://vimdoc.sourceforge.net/htmldoc/change.html#fo-table
set runtimepath+=$HOME/.vim/plugin
set fo=tcq
execute pathogen#infect()

" set default comment color to cyan instead of darkblue
" which is not very legible on a black background
highlight comment ctermfg=brown

set tabstop=2
set expandtab
set softtabstop=2
set shiftwidth=2

highlight LiteralTabs ctermbg=darkgreen guibg=darkgreen
match LiteralTabs /\s\  /
highlight ExtraWhitespace ctermbg=darkgreen guibg=darkgreen
match ExtraWhitespace /\s\+$/

syntax on

" Show me a ruler
set ruler

" ****************************************************************************
" Misc Stuff
" ****************************************************************************
filetype plugin indent on

au BufRead,BufNewFile *.pp set filetype=puppet
